/**
 * ARES - Complete System State Model
 * ES Module Format - Deterministic FSM Architecture
 */

/**
 * 1. SYSTEM STATE MACHINE
 * Controls engine lifecycle.
 */
export enum SystemState {
  BOOTING = "BOOTING",
  SYNCING_DATA = "SYNCING_DATA",
  READY = "READY",
  RUNNING = "RUNNING",
  PAUSED = "PAUSED",
  DEGRADED = "DEGRADED",
  ERROR = "ERROR",
  SHUTDOWN = "SHUTDOWN"
}

/**
 * 2. MARKET REGIME MACHINE
 * Determines macro context.
 */
export enum MarketRegime {
  TRENDING_BULL = "TRENDING_BULL",
  TRENDING_BEAR = "TRENDING_BEAR",
  RANGING = "RANGING",
  VOLATILE_EXPANSION = "VOLATILE_EXPANSION",
  VOLATILE_COMPRESSION = "VOLATILE_COMPRESSION",
  NEWS_EVENT = "NEWS_EVENT",
  UNKNOWN = "UNKNOWN"
}

/**
 * 3. STRUCTURE STATE MACHINE
 * Tracks structural transitions.
 */
export enum StructureState {
  BULLISH_STRUCTURE = "BULLISH_STRUCTURE",
  BEARISH_STRUCTURE = "BEARISH_STRUCTURE",
  TRANSITION = "TRANSITION",

  BOS_CONFIRMED = "BOS_CONFIRMED",
  CHOCH_CONFIRMED = "CHOCH_CONFIRMED",

  LIQUIDITY_SWEEP = "LIQUIDITY_SWEEP",
  EQUILIBRIUM_ROTATION = "EQUILIBRIUM_ROTATION",

  IMPULSE_PHASE = "IMPULSE_PHASE",
  PULLBACK_PHASE = "PULLBACK_PHASE",

  DISTRIBUTION = "DISTRIBUTION",
  ACCUMULATION = "ACCUMULATION",
  NONE = "NONE"
}

/**
 * 4. SIGNAL LIFECYCLE MACHINE
 * Core execution controller.
 */
export enum SignalState {
  IDLE = "IDLE",

  HTF_BIAS_CONFIRMED = "HTF_BIAS_CONFIRMED",
  STRUCTURE_ALIGNED = "STRUCTURE_ALIGNED",

  DISPLACEMENT_DETECTED = "DISPLACEMENT_DETECTED",
  LIQUIDITY_SWEEP_DETECTED = "LIQUIDITY_SWEEP_DETECTED",

  PULLBACK_DETECTED = "PULLBACK_DETECTED",
  REJECTION_CONFIRMED = "REJECTION_CONFIRMED",

  READY_TO_EXECUTE = "READY_TO_EXECUTE",

  ORDER_PLACED = "ORDER_PLACED",
  ORDER_PARTIALLY_FILLED = "ORDER_PARTIALLY_FILLED",
  ORDER_FILLED = "ORDER_FILLED",

  ORDER_CANCELLED = "ORDER_CANCELLED",
  INVALIDATED = "INVALIDATED"
}

/**
 * 5. POSITION STATE MACHINE
 * After execution.
 */
export enum PositionState {
  NONE = "NONE",
  OPEN = "OPEN",
  BREAKEVEN = "BREAKEVEN",
  TRAILING = "TRAILING",

  PARTIAL_TP_HIT = "PARTIAL_TP_HIT",
  FULL_TP_HIT = "FULL_TP_HIT",

  STOP_LOSS_HIT = "STOP_LOSS_HIT",
  FORCE_CLOSED = "FORCE_CLOSED"
}

/**
 * 6. RISK / SAFETY MACHINE
 * Global protection.
 */
export enum RiskState {
  NORMAL = "NORMAL",

  DAILY_DRAWDOWN_LIMIT_HIT = "DAILY_DRAWDOWN_LIMIT_HIT",
  MAX_CONSECUTIVE_LOSSES = "MAX_CONSECUTIVE_LOSSES",

  VOLATILITY_EXCEEDED = "VOLATILITY_EXCEEDED",
  LIQUIDITY_LOW = "LIQUIDITY_LOW",

  API_LATENCY_HIGH = "API_LATENCY_HIGH",

  GLOBAL_KILL_SWITCH = "GLOBAL_KILL_SWITCH"
}

/**
 * 7. LIQUIDITY STATES
 */
export enum LiquidityState {
  ABOVE_EQUAL_HIGH = "ABOVE_EQUAL_HIGH",
  BELOW_EQUAL_LOW = "BELOW_EQUAL_LOW",

  RESTING_BUY_SIDE = "RESTING_BUY_SIDE",
  RESTING_SELL_SIDE = "RESTING_SELL_SIDE",

  SWEPT = "SWEPT",
  UNSWEPT = "UNSWEPT"
}

/**
 * 8. EXECUTION QUALITY
 */
export enum ExecutionQuality {
  CLEAN_FILL = "CLEAN_FILL",
  SLIPPAGE_LOW = "SLIPPAGE_LOW",
  SLIPPAGE_HIGH = "SLIPPAGE_HIGH",
  PARTIAL_FILL = "PARTIAL_FILL"
}

/**
 * COMPLETE ARES STATE SNAPSHOT
 */
export interface AresSnapshot {
  system: SystemState;
  regime: MarketRegime;
  structure: StructureState;
  signal: SignalState;
  position: PositionState;
  risk: RiskState;
  timestamp: number;
}
