export enum KillReason {
  MAX_DAILY_LOSS = "MAX_DAILY_LOSS",
  WS_DISCONNECT = "WS_DISCONNECT",
  ORDER_REJECTED = "ORDER_REJECTED",
  EXECUTION_FAILURE = "EXECUTION_FAILURE",
  SLIPPAGE_EXCEEDED = "SLIPPAGE_EXCEEDED",
  ATR_EXPLOSION = "ATR_EXPLOSION",
  FUNDING_SPIKE = "FUNDING_SPIKE",
  STATE_INCONSISTENT = "STATE_INCONSISTENT",
  MANUAL = "MANUAL",
}
